{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "28d8b50e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "# Import necessary libraries\n",
    "import os\n",
    "import cv2\n",
    "import random\n",
    "import shutil\n",
    "import warnings\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "from tensorflow.keras import layers, models\n",
    "\n",
    "# Ignore warnings\n",
    "warnings.filterwarnings(\"ignore\", category=UserWarning, module=\"urllib3\")\n",
    "\n",
    "# Define base paths\n",
    "base_folder = \"/Users/kisanetgabreselassie/Downloads/archive 2\"\n",
    "output_folder = \"/Users/kisanetgabreselassie/Downloads/archive_2_downsized\"\n",
    "\n",
    "# Define splits and categories\n",
    "sets = ['train', 'test', 'valid']\n",
    "categories = ['wildfire', 'nowildfire']\n",
    "\n",
    "# Ratio for downsizing\n",
    "downsizing_factor = 0.5\n",
    "\n",
    "# Create output directories\n",
    "for dataset in sets:\n",
    "    for category in categories:\n",
    "        new_dir = os.path.join(output_folder, dataset, category)\n",
    "        os.makedirs(new_dir, exist_ok=True)\n",
    "\n",
    "# Function to downsize a dataset\n",
    "def downsize_dataset():\n",
    "    for dataset in sets:\n",
    "        for category in categories:\n",
    "            # Define paths\n",
    "            category_path = os.path.join(base_folder, dataset, category)\n",
    "            new_category_path = os.path.join(output_folder, dataset, category)\n",
    "\n",
    "            # Get list of image files\n",
    "            image_files = os.listdir(category_path)\n",
    "            \n",
    "            # Calculate the number of images to keep\n",
    "            num_images_to_keep = int(len(image_files) * downsizing_factor)\n",
    "\n",
    "            # Randomly sample the images\n",
    "            sampled_images = random.sample(image_files, num_images_to_keep)\n",
    "\n",
    "            # Copy the sampled images to the new downsized dataset\n",
    "            for image_file in sampled_images:\n",
    "                old_image_path = os.path.join(category_path, image_file)\n",
    "                new_image_path = os.path.join(new_category_path, image_file)\n",
    "                shutil.copy(old_image_path, new_image_path)\n",
    "    \n",
    "    print(\"Dataset downsized successfully.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fe55883a-6887-43dd-9498-5333a51799e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset downsized successfully.\n",
      "Found 29991 images belonging to 2 classes.\n",
      "Found 6178 images belonging to 2 classes.\n",
      "Data Generators ready for training.\n"
     ]
    }
   ],
   "source": [
    "downsize_dataset()\n",
    "\n",
    "# Update paths to point to the downsized dataset\n",
    "train_dir = os.path.join(output_folder, 'train')\n",
    "valid_dir = os.path.join(output_folder, 'valid')\n",
    "test_dir = os.path.join(output_folder, 'test')\n",
    "\n",
    "\n",
    "# from PIL import ImageFile\n",
    "#ImageFile.LOAD_TRUNCATED_IMAGES = True\n",
    "\n",
    "\n",
    "train_datagen = ImageDataGenerator(\n",
    "    rescale=1.0/255,\n",
    "    rotation_range=20,\n",
    "    width_shift_range=0.2,\n",
    "    height_shift_range=0.2,\n",
    "    shear_range=0.2,\n",
    "    zoom_range=0.2,\n",
    "    horizontal_flip=True,\n",
    "    fill_mode='nearest'\n",
    ")\n",
    "valid_datagen = ImageDataGenerator(rescale=1.0/255)\n",
    "\n",
    "# Load images from train and validation directories\n",
    "train_generator = train_datagen.flow_from_directory(\n",
    "    train_dir,\n",
    "    target_size=(150, 150),\n",
    "    batch_size=32,\n",
    "    class_mode='binary'  # Assuming binary classification (wildfire vs nowildfire)\n",
    ")\n",
    "valid_generator = valid_datagen.flow_from_directory(\n",
    "    valid_dir,\n",
    "    target_size=(150, 150),\n",
    "    batch_size=32,\n",
    "    class_mode='binary'\n",
    ")\n",
    "print(\"Data Generators ready for training.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "b352ded0-432e-4098-9548-c57349e262e5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.\n",
      "  self._warn_if_super_not_called()\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/15\n",
      "\u001b[1m618/938\u001b[0m \u001b[32m━━━━━━━━━━━━━\u001b[0m\u001b[37m━━━━━━━\u001b[0m \u001b[1m3:36\u001b[0m 677ms/step - accuracy: 0.8454 - loss: 0.3736"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-16 12:18:37.572385: W tensorflow/core/framework/op_kernel.cc:1829] UNKNOWN: OSError: image file is truncated (16 bytes not processed)\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    ret = func(*args)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/ops/from_generator_op.py\", line 198, in generator_py_func\n",
      "    values = next(generator_state.get_iterator(iterator_id))\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py\", line 247, in _finite_generator\n",
      "    yield self.py_dataset[i]\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 68, in __getitem__\n",
      "    return self._get_batches_of_transformed_samples(index_array)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 313, in _get_batches_of_transformed_samples\n",
      "    img = image_utils.load_img(\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/utils/image_utils.py\", line 292, in load_img\n",
      "    img = img.resize(width_height_tuple, resample)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/Image.py\", line 2345, in resize\n",
      "    self.load()\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/ImageFile.py\", line 297, in load\n",
      "    raise OSError(msg)\n",
      "\n",
      "OSError: image file is truncated (16 bytes not processed)\n",
      "\n",
      "\n",
      "2024-11-16 12:18:37.573813: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: UNKNOWN: OSError: image file is truncated (16 bytes not processed)\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    ret = func(*args)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/ops/from_generator_op.py\", line 198, in generator_py_func\n",
      "    values = next(generator_state.get_iterator(iterator_id))\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py\", line 247, in _finite_generator\n",
      "    yield self.py_dataset[i]\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 68, in __getitem__\n",
      "    return self._get_batches_of_transformed_samples(index_array)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 313, in _get_batches_of_transformed_samples\n",
      "    img = image_utils.load_img(\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/utils/image_utils.py\", line 292, in load_img\n",
      "    img = img.resize(width_height_tuple, resample)\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/Image.py\", line 2345, in resize\n",
      "    self.load()\n",
      "\n",
      "  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/ImageFile.py\", line 297, in load\n",
      "    raise OSError(msg)\n",
      "\n",
      "OSError: image file is truncated (16 bytes not processed)\n",
      "\n",
      "\n",
      "\t [[{{node PyFunc}}]]\n",
      "\t [[IteratorGetNext]]\n"
     ]
    },
    {
     "ename": "UnknownError",
     "evalue": "Graph execution error:\n\nDetected at node PyFunc defined at (most recent call last):\n<stack traces unavailable>\nOSError: image file is truncated (16 bytes not processed)\nTraceback (most recent call last):\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n    ret = func(*args)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n    return func(*args, **kwargs)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/ops/from_generator_op.py\", line 198, in generator_py_func\n    values = next(generator_state.get_iterator(iterator_id))\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py\", line 247, in _finite_generator\n    yield self.py_dataset[i]\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 68, in __getitem__\n    return self._get_batches_of_transformed_samples(index_array)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 313, in _get_batches_of_transformed_samples\n    img = image_utils.load_img(\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/utils/image_utils.py\", line 292, in load_img\n    img = img.resize(width_height_tuple, resample)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/Image.py\", line 2345, in resize\n    self.load()\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/ImageFile.py\", line 297, in load\n    raise OSError(msg)\n\nOSError: image file is truncated (16 bytes not processed)\n\n\n\t [[{{node PyFunc}}]]\n\t [[IteratorGetNext]] [Op:__inference_one_step_on_iterator_2049]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnknownError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 26\u001b[0m\n\u001b[1;32m     19\u001b[0m model\u001b[38;5;241m.\u001b[39mcompile(\n\u001b[1;32m     20\u001b[0m     optimizer\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124madam\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m     21\u001b[0m     loss\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mbinary_crossentropy\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m     22\u001b[0m     metrics\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maccuracy\u001b[39m\u001b[38;5;124m'\u001b[39m]\n\u001b[1;32m     23\u001b[0m )\n\u001b[1;32m     25\u001b[0m \u001b[38;5;66;03m# Train the model\u001b[39;00m\n\u001b[0;32m---> 26\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     27\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtrain_generator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     28\u001b[0m \u001b[43m    \u001b[49m\u001b[43msteps_per_epoch\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mlen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mtrain_generator\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     29\u001b[0m \u001b[43m    \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m15\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# Adjust the number of epochs as needed\u001b[39;49;00m\n\u001b[1;32m     30\u001b[0m \u001b[43m    \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mvalid_generator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     31\u001b[0m \u001b[43m    \u001b[49m\u001b[43mvalidation_steps\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mlen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mvalid_generator\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     32\u001b[0m \u001b[43m)\u001b[49m\n\u001b[1;32m     34\u001b[0m \u001b[38;5;66;03m# Save the trained model\u001b[39;00m\n\u001b[1;32m     35\u001b[0m model\u001b[38;5;241m.\u001b[39msave(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mwildfire_prediction_model.h5\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "File \u001b[0;32m~/Library/Python/3.9/lib/python/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/Library/Python/3.9/lib/python/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mUnknownError\u001b[0m: Graph execution error:\n\nDetected at node PyFunc defined at (most recent call last):\n<stack traces unavailable>\nOSError: image file is truncated (16 bytes not processed)\nTraceback (most recent call last):\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n    ret = func(*args)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n    return func(*args, **kwargs)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/tensorflow/python/data/ops/from_generator_op.py\", line 198, in generator_py_func\n    values = next(generator_state.get_iterator(iterator_id))\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py\", line 247, in _finite_generator\n    yield self.py_dataset[i]\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 68, in __getitem__\n    return self._get_batches_of_transformed_samples(index_array)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/legacy/preprocessing/image.py\", line 313, in _get_batches_of_transformed_samples\n    img = image_utils.load_img(\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/keras/src/utils/image_utils.py\", line 292, in load_img\n    img = img.resize(width_height_tuple, resample)\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/Image.py\", line 2345, in resize\n    self.load()\n\n  File \"/Users/kisanetgabreselassie/Library/Python/3.9/lib/python/site-packages/PIL/ImageFile.py\", line 297, in load\n    raise OSError(msg)\n\nOSError: image file is truncated (16 bytes not processed)\n\n\n\t [[{{node PyFunc}}]]\n\t [[IteratorGetNext]] [Op:__inference_one_step_on_iterator_2049]"
     ]
    }
   ],
   "source": [
    "# Build the CNN model\n",
    "from tensorflow.keras import layers, models\n",
    "\n",
    "model = models.Sequential([\n",
    "    layers.Input(shape=(150, 150, 3)),  # Explicit Input layer\n",
    "    layers.Conv2D(32, (3, 3), activation='relu'),\n",
    "    layers.MaxPooling2D((2, 2)),\n",
    "    layers.Conv2D(64, (3, 3), activation='relu'),\n",
    "    layers.MaxPooling2D((2, 2)),\n",
    "    layers.Conv2D(128, (3, 3), activation='relu'),\n",
    "    layers.MaxPooling2D((2, 2)),\n",
    "    layers.Flatten(),\n",
    "    layers.Dense(512, activation='relu'),\n",
    "    layers.Dense(1, activation='sigmoid')  # Output layer for binary classification\n",
    "])\n",
    "\n",
    "\n",
    "# Compile the model\n",
    "model.compile(\n",
    "    optimizer='adam',\n",
    "    loss='binary_crossentropy',\n",
    "    metrics=['accuracy']\n",
    ")\n",
    "\n",
    "# Train the model\n",
    "history = model.fit(\n",
    "    train_generator,\n",
    "    steps_per_epoch=len(train_generator),\n",
    "    epochs=15,  # Adjust the number of epochs as needed\n",
    "    validation_data=valid_generator,\n",
    "    validation_steps=len(valid_generator)\n",
    ")\n",
    "\n",
    "# Save the trained model\n",
    "model.save('wildfire_prediction_model.h5')\n",
    "print(\"hello\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12f65e80-82fc-4a18-b283-94fe7365c1b1",
   "metadata": {},
   "outputs": [],
   "source": [
    "loss, accuracy = model.evaluate(valid_generator)\n",
    "print(f\"Validation Loss: {loss}\")\n",
    "print(f\"Validation Accuracy: {accuracy}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fe5d4091-98c7-4fd7-b996-5c05e3c0e7f2",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "52503bfc-7705-449a-917c-81e867c75bf5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0e2581c-2762-497e-9b35-c0da01a9415c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
